name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - "*.x"
      - "main"
      - "master"
    tags:

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
